### PR TITLE
Ensures input to subset_variables is a list

### PR DESCRIPTION
**Pull request by pwolfram**
Prevents errors when onlyvars is a string.

### CODE REVIEW

**Comment by pwolfram** [comment]
cc @milenaveneziani because this fixes a bug when onlyvars is a string.  Please review before I merge.

**Comment by milenaveneziani** [comment]
@pwolfram: I tested this on the globalstats data set I showed you earlier, and it worked. Go ahead and merge it. thanks.

**Comment by pwolfram** [comment]
Thanks @milenaveneziani!

**Comment by pwolfram** [comment]
@milenaveneziani, just updated this on titan via pip: `pip -v install git+ssh://git@github.com/pwolfram/mpas_xarray`-- when you get a chance can you please make sure that the natively installed version (0.0.2) does everything you need for the analysis now?  Thanks!

**Comment by milenaveneziani** [comment]
sure, will do!

**Pull request merged**
