### PR TITLE
Generalizes time relative to record start

### PR DESCRIPTION
**Pull request by pwolfram**
This addresses an issue to allow MPAS time record to be set based on days since the start of the record and is implemented to provide for comparisons with POP data sets using xray (xarray).

### CODE REVIEW

**Comment by pwolfram** [comment]
@milenaveneziani, can you try this out to see if it works for you and resolves the issue with MPAS reading having strange dates?  You want to take a look at https://github.com/pwolfram/mpas_xray_wrapper/commit/713587a7eaab73d6ad32ca1d3eccc5fd982b0e35#diff-04c6e90faac2675aa89e2176d2eec7d8R39 for usage.

**Comment by pwolfram** [comment]
This should resolve problems identified in #2.

**Comment by milenaveneziani** [comment]
@pwolfram : before testing this, I had to adjust for the following: 1) make all calls to xarray, since I have updated to the latest xarray version (and 'import xray' was not working); 2) change the usedatetime switch to False (I did that in the script itself, but perhaps there is a way to 'pass' it to the preprocess routine?). Then I tried the test, but it failed with the following messages (related to my use of xarray..):

screen shot 2016-02-24 at 11 44 19 pm

do you understand what is wrong?

**Comment by pwolfram** [comment]
@milenaveneziani, I just submitted #3 to handle your first comment.  This PR incorporates that change.  Secondly, I'm running this with code like

```
import xarray as xr

from mpas_xarray import preprocess_mpas, remove_repeated_time_index

def preprocess_mpas_time_days(ds):
    return preprocess_mpas(ds, usedatetime=False)

ds = xr.open_mfdataset('globalStats*nc', preprocess=preprocess_mpas_time_days)                  
ds = remove_repeated_time_index(ds)
```

You can get the testing script at https://gist.github.com/0fbf4583110c67f2c87d

There should be no hard-coding required although you could argue the new function essentially performs hard coding.  The point is we don't need to change mpas_xarray.

If I run this code things appear to work with the new branch.  Can you please check it out and let me know, specifically whether this works now that you've updated to xarray?  I'd like to merge #3 and please feel free to comment / review.

**Comment by milenaveneziani** [comment]
@pwolfram I have tested #3 and it worked in my OHC script, so you can merge that if you like. Also, since you changed the routine's name to mpas_xarray, people using the old routine (with old handling of time) should not be affected at the moment.
I will go ahead and test the changes you made for this PR now.

**Comment by milenaveneziani** [comment]
@pwolfram : I still get the error I posted yesterday. Here is what I do:
`# Load year-1 data and compute first-year average`
`def preprocess_mpas_time_days(ds_yr1):`
`return preprocess_mpas(ds_yr1, usedatetime=False)`
`ds_yr1 = xr.open_mfdataset(infiles_yr1,preprocess=preprocess_mpas_time_days)`
`ds_yr1 = remove_repeated_time_index(ds_yr1)`
`mean_yr1 = ds_yr1.mean('Time')`
(note that there is an indentation before 'return preprocess_mpas' in my code..)

resulting in:
screen shot 2016-02-25 at 11 37 32 am

**Comment by pwolfram** [comment]
Following discussions with @milenaveneziani, we have decided to retrofit POP output with an `xtime`-like field so that the standard MPAS wrapper can be used.

**Pull request closed without merging**
