### PR TITLE
Fixes version number and module interface

### PR DESCRIPTION
**Pull request by pwolfram**
Neglected to update version number and interface to module in previous commits.

### CODE REVIEW

**Comment by pwolfram** [comment]
@vanroekel, this was a mistake from the previous commit.  I know you use the wrapper in installation mode.  Do you mind testing that this works correctly in your workflows for me?

**Comment by vanroekel** [comment]
@pwolfram, sorry for the delay on this.  It had slipped off my radar.  Testing now.

**Comment by vanroekel** [comment]
@pwolfram, confirming that this change works for me.  Tested on rhea.

**Comment by pwolfram** [comment]
Thanks @vanroekel!

@milenaveneziani, do you want to test this too?  I think it should be ready to go without further testing because it is a minor change and it should not break the current analysis workflow because `mpas_xarray.py` is essentially "installed" as a local module, not via pip.  If you don't think you need to test this (and I don't think this is necessary) I'd like to merge it sometime today.  Thanks!

**Comment by milenaveneziani** [comment]
No, @pwolfram, I don't think I need to test this. Go ahead with the merge.

**Pull request merged**
