### PR TITLE
Update to xarray following library rename

### PR DESCRIPTION
**Pull request by pwolfram**
This is a maintenance PR that addresses the rename of xray to xarray.
- Updates to xarray 
- handles deflated netCDF4 via gitignore

### CODE REVIEW

**Comment by pwolfram** [comment]
@jonwoodring and @toddringler: do either of you mind taking a quick look at this before I merge it?  I'm asking because I know you use this code and don't want to break it for you.  It should be simple because it just addresses the xarray rename.  Thanks, Phillip

**Comment by pwolfram** [comment]
@milenaveneziani, do you mind making sure this doesn't break your workflow either?  Thanks, Phillip

**Comment by pwolfram** [comment]
Note, I also need to rename this repo to `mpas_xarray_wrapper` following this merge.

**Comment by ghost** [comment]
I'm not currently using xray/xarray in my stuff, but I looked at it. Looks OK to me.

**Comment by pwolfram** [comment]
It sounds like this is ok so I will merge it for forward compatibility with xarray.

**Pull request merged**
