### PR TITLE
Make module into a pacakge

### PR DESCRIPTION
**Pull request by pwolfram**
Packages module so it can be installed via

`pip -v install git+ssh://git@github.com/pwolfram/mpas_xarray` (once merged)

or to test prior to merge: 
`pip -v install git+ssh://git@github.com/pwolfram/mpas_xarray@pip_package`

Then, module functions will be available via a simple
`from mpas_xarray import *` within a python session.

### CODE REVIEW

**Comment by pwolfram** [comment]
Addresses issue #7

**Comment by pwolfram** [comment]
@milenaveneziani, can we say that this PR is ready to merge?

**Comment by milenaveneziani** [comment]
yes, @pwolfram . Thanks.

**Comment by pwolfram** [comment]
Thanks @milenaveneziani!

**Pull request merged**
